### ISSUE TITLE
cant get this to work

### ISSUE THREAD

**Issue by loeffelstiel** [NicoSchlueter/Reverse#2]
hi,
install works fine, but im really struggling with your instructions.

"The Commands will appear as SURFACE > CREATE"
and those commands are? SURFACE > CREATE > 'Cylinder or 'Plane'? a little cryptic.

"Reconstructs BRep Surfaces from mesh points."
does this work for mesh bodies or BRep bodies? i cant select BReps bodies, so im guessing mesh bodies, right?

"2. Activate the command for the desired feature type. Select the mesh and select mesh points belonging to that feature."
i can select a mesh, but no points. am i even using the right command? the addin is running.

**Comment by phossystems** [comment]
The Add-In creates (B-Rep) Surfaces from mesh bodies.

Cylinder is used to create a cylindrical surface, Plane is used to create a planter surface.

You can select vertices by clicking on them, and deselect them by clicking on them while holding shift. You can increase or decrease the selection radius to allow for easier selection.

Here is a quick demonstration showing how to reconstruct a few surface of this mesh:
https://www.youtube.com/watch?v=fbMya0XWqIU

Hope this helps
